### ISSUE TITLE
向数组添加元素过多时 Gas 会超出 Block 的 Gaslimit

### ISSUE THREAD

**Issue by jindada1** [ACC-CON/IoT-Device-Rental-Platform#12]
向数据结构的添加元素的时候消耗 Gas 的问题

代码在 `test/GenerateSessionID.js` 中，点击[此处](https://github.com/ACC-CON/IoT-Device-Rental-Platform/blob/gas_estimate/test/GenerateSessionID.js#L69-L108)跳转

报错为：
> Error: exceeds block gas limit

如果在合约的构造函数中初始化好数据结构，是否能够部署成功（部署消耗的 gas 够吗）？

**Comment by jindada1** [comment]
合约中存在以下代码

```solidity
pragma solidity ^0.5.17;
pragma experimental ABIEncoderV2;

contract Operations {
    // ...
    struct Auth {
        bytes from;
        bytes to;
        uint256 expire;
        bool right;
    }

    // mapping(Iotid => Device)
    // maintaining all the authorized list for all IoT devices
    mapping(uint32 => Auth[]) public accTab;
    
    // 向 accTab[IoTid] 中添加指定数量的 Auth 实例
    function addFakeItemsInAccTab(
        uint32 IoTid,
        uint256 num
    ) public {
        for (uint256 index = 0; index < num; index++) {
            accTab[IoTid].push(
                Auth({from: "fakefrom", to: "faketo", expire: now, right: true})
            );
        }
    }

    // ...
}
```

在 test/GenerateSessionID.js 中

```javascript
contract('Operations', (accounts) => {
    const length1 = 100;
    it(`should get ${title}, length of accTab[IoTid] is ${length1}`, async () => {
        const contractInstance = await Operations.deployed();
        // ...
        // 想要调用合约提供的函数向 accTab[IoTid] 实现中添加 99 个元素
        const result = await contractInstance.addFakeItemsInAccTab(uint32_id, length1 - 1, {
            from: richman,
            gas: 850000000000,
            gasPrice: 200
         })
        ...
    });
});
```

报错：
```
  1 failing

  1) Contract: Operations
       should get gas used by [GenerateSessionID], length of accTab[IoTid] is 100:
     Error: Returned error: Exceeds block gas limit
      at Context.<anonymous> (test\GenerateSessionID.js:94:47)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)



npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iot-device-rental-platform@1.0.0 test: `truffle test ".\test\GenerateSessionID.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iot-device-rental-platform@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Kris\AppData\Roaming\npm-cache\_logs\2021-05-16T08_08_44_216Z-debug.log
```
关键错误：`Error: Returned error: Exceeds block gas limit`

**Comment by KofClubs** [comment]
I shall work on it.

**Comment by KofClubs** [comment]
Please refer to the branch [test-addFakeItemsInAccTab](https://github.com/ACC-CON/IoT-Device-Rental-Platform/tree/test-addFakeItemsInAccTab).

I put the contract function `addFakeItemsInAccTab` to be tested in the file [TestOperations.sol](https://github.com/ACC-CON/IoT-Device-Rental-Platform/blob/test-addFakeItemsInAccTab/contracts/TestOperations.sol).

See the file [TestOperations.evm](https://github.com/ACC-CON/IoT-Device-Rental-Platform/blob/test-addFakeItemsInAccTab/contracts/TestOperations/TestOperations.evm) for its EVM code.

We shall note that the fee of the `SSTORE` operation is variable. According to [Ethereum Yellow Paper](https://ethereum.github.io/yellowpaper/paper.pdf),

> *G_sset* = 20000 (Paid for an SSTORE operation when the storage value is set to non-zero from zero.)
> *G_sreset* = 5000 (Paid for an SSTORE operation when the storage value’s zeroness remains unchanged or
is set to zero.)

The initial key space of the `mapping` data type is the full range, so inserting a new value is an `sset` operation.

Reference reading:

[solidity - Differentiate between an unset value and 0 in an mapping - Ethereum Stack Exchange](https://ethereum.stackexchange.com/questions/28549/differentiate-between-an-unset-value-and-0-in-an-mapping)

*To be continued...*

**Comment by KofClubs** [comment]
Don't put the write operation loop in the contract. We shall call it repeatedly to avoid exceeding the `gasLimit`.
