### ISSUE TITLE
HMAC_SHA512

### ISSUE THREAD

**Issue by jindada1** [ACC-CON/IoT-Device-Rental-Platform#9]
ckdpub_solidity分支

CKDPub.sol 中的 HMAC_SHA512 方法的结果可能不对，需要进一步验证与修改

这个方法矫正成功后就可以验证 driveChildPub 方法了

**Comment by jindada1** [comment]
可能有用的链接：https://www.ipa.go.jp/security/rfc/RFC4868EN.html

**Comment by KofClubs** [comment]
I shall fix it as soon as possible.

**Comment by jindada1** [comment]
https://en.wikipedia.org/wiki/HMAC

**Comment by jindada1** [comment]
ok
